apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: cms

type: Opaque

stringData:
  DB_USERNAME: postgres
  DB_PASSWORD: "1234"

  EMAIL_USERNAME: haiqua073@gmail.com
  EMAIL_PASSWORD: acnz cfvm lugb idbe

  JWT_SECRET: "mySuperStrongJwtSecretKey123456789"