name: SonarCloud Scan

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # IMPORTANT for SonarCloud

      # Setup Java for backend
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Setup Node for frontend
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # FRONTEND
      - name: Install Frontend
        working-directory: ./frontend
        run: npm install

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      # BACKEND (FIXED)
      - name: Build Backend
        working-directory: ./backend
        run: mvn clean verify

      # SONAR CLOUD (IMPORTANT FIX)
      - name: SonarCloud Scan
        working-directory: ./backend
        run: mvn sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}